name: Change issue label

on:
  issues:
    types: [labeled]
defaults:
  run:
    shell: powershell

jobs:
  delete-labels:
    runs-on: windows-latest
    steps:
      - name: dump github context
        run: echo '${{ toJson(github.event) }}'

      - name: Check issue label
        if: github.event.action == 'labeled' && github.event.label.name == 'help wanted'
        run: echo "Issue has a specific label"

            
      - name: Delete labels
        if: github.event.action == 'labeled' && github.event.label.name == 'help wanted'
        env:
          GH_TOKEN: ${{secrets.TOKEN_1}}
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          curl -L -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$OWNER/$REPO/issues/$ISSUE_NUMBER/labels
        