name: Change issue label

on:
  issues:
    types: [labeled]
defaults:
  run:
    shell: powershell

jobs:
  delete-labels:
    runs-on: windows-latest
    steps:
      - name: dump github context
        run: echo '${{ toJson(github.event) }}'

      - name: Check issue label
        if: github.event.action == 'labeled' && github.event.label.name == 'help wanted'
        run: echo "Issue has a specific label"

            
      - name: Delete labels
        if: github.event.action == 'labeled' && github.event.label.name == 'help wanted'
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
            gh api repos/$OWNER/$REPO/issues/$ISSUE_NUMBER/labels --method DELETE -H "Accept: application/vnd.github.v3+json"
        