name: Build exe from py

on:
  pull_request:
    types: [labeled]
    branches:
        - main
defaults:
  run:
    shell: powershell

jobs:
    create-exe-artifact:
        runs-on: windows-latest
        if: github.event.action == 'labeled' && github.event.label.name == 'exe-creation'
        steps:
            - name: Dump github context
              run: echo '${{ toJson(github.event) }}'

            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10.11'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pyinstaller

            - name: Build exe
              run: |
                Write-Host "Current directory: $PWD"
                cd scripts
                python -m PyInstaller writeOnFile.py --onefile