name: Close every pull request

on:
  pull_request:
    branches:
        - main
defaults:
  run:
    shell: powershell

jobs:
    block-pull-req:
        runs-on: windows-latest

        steps:
            
            - name: Open issue
              env:
                GH_TOKEN: ${{secrets.MY_TOKEN}}
                OWNER: ${{ github.event.repository.owner.login }}
                REPO: ${{ github.event.repository.name }}
                PULL_REQ_ID: ${{github.event.pull_request.id}}
                PULL_REQ_INFO: ${{github.event.pull_request.title}}
                EVENT_AUTHOR: ${{github.event.pull_request.user.login}}
              run: |
                $headers = @{
                    "Authorization" = "Bearer $env:GH_TOKEN"
                }
                $uri = "https://api.github.com/repos/$env:OWNER/$env:REPO/issues"
                $body = @{
                    title = "Issue opened from pull request"
                    body = " @$env:EVENT_AUTHOR you cannot make a pull request now
                            PULL REQUEST INFO:
                                ID: $env:PULL_REQ_ID
                                TITLE $env:PULL_REQ_INFO"
                    labels = @("invalid")
                } | ConvertTo-Json
                Invoke-WebRequest -Uri $uri -Method Post -Headers $headers -Body $body

            - name: Block pull request
              env:
                GH_TOKEN: ${{secrets.MY_TOKEN}}
                OWNER: ${{ github.event.repository.owner.login }}
                REPO: ${{ github.event.repository.name }}
                PULL_REQ_ID: ${{github.event.pull_request.id}}
                PULL_NUMBER: ${{github.event.pull_request.number}}
                PULL_REQ_TITLE: ${{github.event.pull_request.title}}
                EVENT_AUTHOR: ${{github.event.pull_request.user.login}}
              run: |
                $headers = @{
                    "Authorization" = "Bearer $env:GH_TOKEN"
                }
                $uri = "https://api.github.com/repos/$env:OWNER/$env:REPO/pulls/$env:PULL_NUMBER"
                $body = @{
                    title = $PULL_REQ_TITLE
                    body = " @$env:EVENT_AUTHOR you cannot make a pull request now
                            PULL REQUEST INFO:
                                ID: $env:PULL_REQ_ID
                                TITLE: $env:PULL_REQ_TITLE"
                    state = "closed"
                    labels = @("invalid")
                } | ConvertTo-Json
                Invoke-WebRequest -Uri $uri -Method Post -Headers $headers -Body $body