name: Run Python Script

on:
  workflow_dispatch:
defaults:
  run:
    shell: powershell

jobs:
  run-python-script:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Script
        run: |
          cd scripts
          .\writeOnFile.exe tmp/test.log
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-art
          path: ${{github.workspace}}/scripts/tmp
          retention-days: 1
