name: Run Python Script

on:
  workflow_dispatch:
    

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Script
      run: |
        cd scripts
        writeOnFile.exe