name: Run Python Script

on:
  workflow_dispatch:
    

jobs:
  make-dir:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: create dir
      run: |
        mkdir -p Pipelines/tmpFiles
