name: Run Python Script

on:
  workflow_dispatch:
defaults:
  run:
    shell: powershell

jobs:
  run-python-script:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Script
        run: |
          cd scripts
          mkdir ${{github.workspace}}\tmp
          .\writeOnFile.exe >  "${{github.workspace}}\tmp\test.txt"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-art
          path: ${{github.workspace}}\tmp\test.txt
          retention-days: 1
