name: Run Python Script

on:
  workflow_dispatch:
defaults:
  run:
    shell: powershell
    

jobs:
  run-python-script:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create file
      run: touch test.txt
    - name: Run Script
      run: |
        cd scripts
        ./writeOnFile.exe > test.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-art
        path: tmp
