name: Run Python Script

on:
  workflow_dispatch:
defaults:
  run:
    shell: powershell
    

jobs:
  run-python-script:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Debug
      run: |
        pwd
        Get-ChildItem -Force -Path scripts
        if (Test-Path "scripts/writeOnFile.exe") { 
          echo "File 'writeOnFile.exe' found" 
        } else { 
          echo "File 'writeOnFile.exe' not found" 
        }
    
    - name: Run Script
      run: |
        cd scripts
        Invoke-Expression -Command ".\writeOnFile.exe" | Out-File -FilePath "test.txt"
#    - name: Upload artifact
#      uses: actions/upload-artifact@v4
#      with:
#        name: my-art
#        path: test.txt
